### ISSUE TITLE
EX99 9NF is valid UK postcode, but actually NOT

### ISSUE THREAD

**Issue by alexey-klimuk** [threedaymonk/uk_postcode#6]
The gem treat "EX99 9NF" postcode as valid:
`[2] pry(main)> UKPostcode.parse("EX99 9NF").valid?
=> true`
`[3] pry(main)> UKPostcode.parse("EX99 9NF").full_valid?
=> true`

**Comment by threedaymonk** [comment]
Is this invalid (and if so, why?) or is it not assigned?

**Comment by alexey-klimuk** [comment]
https://www.google.by/maps/search/EX99+9NF

**Comment by threedaymonk** [comment]
Is your issue that `EX99 9NF` is not a real place?

There's a distinction between validity and existence. This library validates the *format* of a postcode, but not whether it actually currently refers to a location.

By analogy, `name@somedomainthatdoesnotexist.com` is a valid email address in terms of format, but you can't successfully deliver an email to it.

**Comment by alexey-klimuk** [comment]
@threedaymonk thanks, closing the issue
